services: 
    python-api:
        build:
            context: ./python_api
        image: skogrv/python-api:3.1
        read_only: true
        depends_on:
            - db
        ports: 
            - "5000:5000"
        expose:
            - "5000"
    db: 
        build:
            context: ./db
        image: skogrv/db:1.2
        env_file: .env
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: postgres
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            POSTGRES_DB: postgres
        ports: 
            - "5432:5432"
        volumes: 
            - pgdata:/var/lib/postgres/data
        expose:
            - "5432"
volumes:
    pgdata:

