services: 
    python-api:
        build:
            context: ./python_api
        image: skogrv/python-api:3.1
        depends_on:
            - db
        ports: 
            - "5000:5000"
        expose:
            - "5000"
    db: 
        build:
            context: ./db
        image: skogrv/db:1.2
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            POSTGRES_DB: postgres
        ports: 
            - "5432:5432"
        expose:
            - "5432"

